version: "3.7"
services:
  apache:
    image: treaudde/simple-development-environment:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: notes-app
      DB_USERNAME: notes
      DB_PASSWORD: insecure_password

  mysql:
    image: mysql:5
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notes-app
      MYSQL_USER: notes
      MYSQL_PASSWORD: insecure_password



