version: "3.7"
services:
  notes-backend:
    container_name: notes-app-backend
    image: treaudde/simple-development-environment:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_CONNECTION: mysql
      DB_HOST: notes-database
      DB_PORT: 3306
      DB_DATABASE: notes-app
      DB_USERNAME: notes
      DB_PASSWORD: insecure_password

  notes-frontend:
    container_name: notes-app-frontend
    image: treaudde/simple-development-environment:latest
    ports:
      - "8081:80"
      - "8082:4200"
    volumes:
      - ./frontend:/var/www/html

  notes-database:
    container_name: notes-app-database
    image: mysql:5
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notes-app
      MYSQL_USER: notes
      MYSQL_PASSWORD: insecure_password



